# unittests using the 'latest' runtime python-dependencies
task:
  name: "build: Windows"
  container:
    dockerfile: contrib/build-wine/Dockerfile
    cpu: 1
    memory: 3G
  pip_cache:
    folders:
      - contrib/build-wine/.cache/win*/wine_pip_cache
    fingerprint_script:
      - echo $CIRRUS_TASK_NAME
      - git ls-files -s contrib/deterministic-build/*.txt
      - git ls-files -s contrib/build-wine/
  build2_cache:
    folders:
      - contrib/build-wine/.cache/win*/build
    fingerprint_script:
      - echo $CIRRUS_TASK_NAME
      - cat contrib/make_libsecp256k1.sh | sha256sum
      - cat contrib/make_libusb.sh | sha256sum
      - cat contrib/make_zbar.sh | sha256sum
      - git ls-files -s contrib/build-wine/
  build_script:
    - cd contrib/build-wine
    - ./make_win.sh
  binaries_artifacts:
    path: "contrib/build-wine/dist/*"
  env:
    CIRRUS_WORKING_DIR: /opt/wine64/drive_c/electrum-grs
    CIRRUS_DOCKER_CONTEXT: contrib/build-wine

task:
  name: "build: Android (QML $APK_ARCH)"
  timeout_in: 90m
  container:
    dockerfile: contrib/android/Dockerfile
    cpu: 8
    memory: 24G
  env:
    APK_ARCH: arm64-v8a
  packages_tld_folder_cache:
    folder: packages
    fingerprint_script:
      - echo $CIRRUS_TASK_NAME && cat contrib/deterministic-build/requirements.txt && cat contrib/make_packages.sh
      - git ls-files -s contrib/android/
  p4a_cache:
    folders:
      - ".buildozer/android/platform/build-$APK_ARCH/packages"
      - ".buildozer/android/platform/build-$APK_ARCH/build"
    fingerprint_script:
      # note: should *at least* depend on Dockerfile and p4a_recipes/, but contrib/android/ is simplest
      - git ls-files -s contrib/android/
      - echo "qml $APK_ARCH"
  build_script:
    - ./contrib/android/make_apk.sh qml "$APK_ARCH" debug
  binaries_artifacts:
    path: "dist/*"

#task:
#  name: "build: macOS"
#  macos_instance:
#    image: ghcr.io/cirruslabs/macos-monterey-xcode:13.3.1
#  env:
#    TARGET_OS: macOS
#  pip_cache:
#    folder: ~/Library/Caches/pip
#    fingerprint_script:
#      - echo $CIRRUS_TASK_NAME
#      - git ls-files -s contrib/deterministic-build/*.txt
#      - git ls-files -s contrib/osx/
#  build2_cache:
#    folder: contrib/osx/.cache
#    fingerprint_script:
#      - echo $CIRRUS_TASK_NAME
#      - cat contrib/make_libsecp256k1.sh | shasum -a 256
#      - cat contrib/make_libusb.sh | shasum -a 256
#      - cat contrib/make_zbar.sh | shasum -a 256
#      - git ls-files -s contrib/osx/
#  install_script:
#    - git fetch --all --tags
#  build_script:
#    - ./contrib/osx/make_osx.sh
#  sum_script:
#    - ls -lah dist
#    - shasum -a 256 dist/*.dmg
#  binaries_artifacts:
#    path: "dist/*"

task:
  name: "build: AppImage"
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 2
    memory: 2G
  pip_cache:
    folder: contrib/build-linux/appimage/.cache/pip_cache
    fingerprint_script:
      - echo $CIRRUS_TASK_NAME
      - git ls-files -s contrib/deterministic-build/*.txt
      - git ls-files -s contrib/build-linux/appimage/
  build2_cache:
    folder: contrib/build-linux/appimage/.cache/appimage
    fingerprint_script:
      - echo $CIRRUS_TASK_NAME
      - cat contrib/make_libsecp256k1.sh | sha256sum
      - git ls-files -s contrib/build-linux/appimage/
  build_script:
    - ./contrib/build-linux/appimage/build.sh
  binaries_artifacts:
    path: "dist/*"
  env:
    CIRRUS_DOCKER_CONTEXT: contrib/build-linux/appimage

task:
  container:
    dockerfile: contrib/build-linux/sdist/Dockerfile
    cpu: 1
    memory: 1G
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script:
      - echo $CIRRUS_TASK_NAME
      - git ls-files -s contrib/deterministic-build/*.txt
      - git ls-files -s contrib/build-linux/sdist/
  build_script:
    - ./contrib/build-linux/sdist/make_sdist.sh
  binaries_artifacts:
    path: "dist/*"
  matrix:
    - name: "build: tarball"
    - name: "build: source-only tarball"
      env:
        OMIT_UNCLEAN_FILES: 1

task:
  name: "check submodules"
  container:
    image: python:3.10
    cpu: 1
    memory: 1G
  fetch_script:
    - git fetch --all --tags
  check_script:
    - ./contrib/deterministic-build/check_submodules.sh
  only_if: $CIRRUS_TAG != ''
